#include "arx/features/arx_pedal_controller.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

int main(void) {
    ArxPedalController p;
    arx_pedal_init(&p);

    assert(ARX_PEDAL_UART_BAUD == 9600u);
    assert(arx_pedal_set_mode(&p, ARX_PEDAL_AUTO));
    assert(arx_pedal_set_power(&p, 0));

    assert(arx_pedal_target_map(&p, ARX_DNA_NATURAL) == ARX_PEDAL_MAP_NATURAL);
    assert(arx_pedal_target_map(&p, ARX_DNA_DYNAMIC) == ARX_PEDAL_MAP_DYNAMIC);
    assert(arx_pedal_target_map(&p, ARX_DNA_ALL_WEATHER) == ARX_PEDAL_MAP_ALL_WEATHER);
    assert(arx_pedal_target_map(&p, ARX_DNA_RACE) == ARX_PEDAL_MAP_RACE);

    uint8_t packet[ARX_PEDAL_PACKET_SIZE];
    /* Reference literals derived from upstream setSchizzaforteMap and calculateCRC,
       commit efd407205ee8513d3aa9c39fcfb1c59f49b0b5a6; not generated by ARX. */
    const uint8_t reference[5][9]={
        {0x23,0xB6,0,0,0,0,0,0,0x83},
        {0x23,0xB6,0x49,0x60,0x80,0x9A,0,0,0x23},
        {0x23,0xB6,0x92,0x80,0x80,0x9A,0,0,0x7A},
        {0x23,0xB6,0xDB,0xC0,0x80,0x9A,0,0,0xF9},
        {0x23,0xB6,0x24,0xE6,0x80,0x9A,0,0,0x50}
    };
    for(unsigned i=0;i<5;i++){
        assert(arx_pedal_build_map_packet(&p,(ArxPedalMap)(i+1),packet));
        assert(memcmp(packet,reference[i],sizeof(packet))==0);
    }
    assert(arx_pedal_build_map_packet(&p, ARX_PEDAL_MAP_DYNAMIC, packet));
    assert(packet[0] == '#');
    assert(packet[1] == 0xB6u);
    assert(packet[2] == 0xDBu);
    assert(packet[3] == 192u);
    assert(packet[4] == 128u);
    assert(packet[5] == 154u);

    arx_pedal_on_reply(&p, 0xEBu);
    assert(p.applied_map == ARX_PEDAL_MAP_DYNAMIC);

    assert(arx_pedal_set_mode(&p, ARX_PEDAL_HYBRID_ALIGN));
    assert(arx_pedal_target_map(&p, ARX_DNA_DYNAMIC) == ARX_PEDAL_MAP_NATURAL);
    assert(arx_pedal_target_map(&p, ARX_DNA_RACE) == ARX_PEDAL_MAP_RACE);

    assert(arx_pedal_set_mode(&p, ARX_PEDAL_KIDS_LIMITER));
    assert(arx_pedal_kids_override_required(&p, true, 3100u, 50.0f));
    assert(arx_pedal_kids_override_required(&p, true, 2000u, 101.0f));
    assert(!arx_pedal_kids_override_required(&p, true, 2000u, 50.0f));
    assert(arx_pedal_build_zero_override(&p, packet));
    assert(packet[1] == 0xFFu && packet[2] == 0x00u);

    arx_pedal_init(&p);
    assert(!arx_pedal_set_mode(&p,(ArxPedalMode)-1));
    assert(!arx_pedal_set_power(&p,11));
    assert(!arx_pedal_build_map_packet(&p,ARX_PEDAL_MAP_UNKNOWN,packet));
    assert(arx_pedal_set_mode(&p,ARX_PEDAL_DYNAMIC));
    assert(arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,800,0,0,packet));
    arx_pedal_note_send(&p,false,0);
    assert(p.communication==ARX_PEDAL_COMM_TX_ERROR && p.tx_count==0);
    assert(!arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,800,0,400,packet));
    assert(arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,800,0,401,packet));
    arx_pedal_note_send(&p,true,401);
    arx_pedal_on_reply_at(&p,0xA2,410);
    assert(p.communication==ARX_PEDAL_COMM_MAP_MISMATCH);
    assert(arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,800,0,802,packet));
    arx_pedal_note_send(&p,true,802);
    arx_pedal_on_reply_at(&p,0xEB,810);
    assert(p.communication==ARX_PEDAL_COMM_MAP_CONFIRMED);
    assert(!arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,800,0,1300,packet));
    assert(arx_pedal_set_power(&p,10));
    assert(arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,800,0,1300,packet));
    assert(packet[3]==212); /* upstream Dynamic amplitude192 +10*2 */
    arx_pedal_note_send(&p,true,1300);
    arx_pedal_tick(&p,true,1401);
    assert(p.communication==ARX_PEDAL_COMM_TIMEOUT && !p.waiting_reply);
    arx_pedal_on_reply_at(&p,0xEB,1402);
    assert(p.applied_map==ARX_PEDAL_MAP_UNKNOWN); /* late byte is not confirmation */
    assert(arx_pedal_set_mode(&p,ARX_PEDAL_DISABLED));
    assert(arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,false,true,0,0,1701,packet));
    assert(packet[2]==0); /* Explicit disable requests bypass before stopping. */
    arx_pedal_note_send(&p,true,1701);arx_pedal_on_reply_at(&p,0x10,1710);
    assert(!p.disable_pending);
    assert(!arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,800,0,2200,packet));
    assert(arx_pedal_set_mode(&p,ARX_PEDAL_KIDS_LIMITER));
    assert(arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,3100,101,2300,packet));
    assert(packet[1]==0xB6 && packet[2]==0x49 && packet[3]==90);
    arx_pedal_note_send(&p,true,2300);arx_pedal_on_reply_at(&p,0x59,2310);
    assert(!arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,3100,101,2700,packet));
    assert(arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,3100,101,2701,packet));
    assert(packet[1]==0xFF && packet[2]==0);
    arx_pedal_note_send(&p,true,2701);
    assert(!arx_pedal_prepare_packet(&p,ARX_DNA_NATURAL,true,true,3100,101,2702,packet));
    /* Upstream-derived amplitudes at min/neutral/max; not generated by ARX. */
    const int8_t powers[3]={-10,0,10};
    const uint8_t amplitudes[4][3]={{90,96,112},{112,128,160},{160,192,212},{212,230,254}};
    for(unsigned m=0;m<4;m++)for(unsigned v=0;v<3;v++){
        assert(arx_pedal_set_power(&p,powers[v]));
        assert(arx_pedal_build_map_packet(&p,(ArxPedalMap)(ARX_PEDAL_MAP_ALL_WEATHER+m),packet));
        assert(packet[3]==amplitudes[m][v] && packet[4]==128 && packet[5]==154);
    }
    puts("pedal controller tests: OK");
    return 0;
}
