<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AlfaRaceX-Updater</AssemblyName>
    <RootNamespace>AlfaRaceX.Updater</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
    <Version>0.5.1</Version>
    <ApplicationIcon>Assets\ARX.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\AlfaRaceX-Splash.jpg" LogicalName="AlfaRaceX.Splash.jpg" />
    <EmbeddedResource Include="Assets\ARX-256.png" LogicalName="AlfaRaceX.ARX.png" />
    <EmbeddedResource Include="Assets\ARX-Hero.jpg" LogicalName="AlfaRaceX.Hero.jpg" />
    <EmbeddedResource Include="Assets\ARX-Watermark.jpg" LogicalName="AlfaRaceX.Watermark.jpg" />
  </ItemGroup>
</Project>
