const { JSDOM } = require('node:module').createRequire(require('node:path').join(__dirname, '../AlfaRaceX.Desktop/package.json'))('jsdom');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.join(__dirname, '../AlfaRaceX.Desktop/wwwroot');
const dom = new JSDOM(fs.readFileSync(path.join(root, 'index.html'), 'utf8'), { runScripts:'outside-only' });
const w = dom.window, doc = w.document, sent = [];
let receiver;
w.chrome = { webview: { postMessage:m=>sent.push(m), addEventListener:(_, fn)=>receiver=fn } };
w.confirm = ()=>true;
w.eval(fs.readFileSync(path.join(root,'js/app.js'),'utf8'));
const receive = (type,data)=>receiver({data:{type,data}});
assert.deepEqual(sent.map(x=>x.action), ['initialize']);
assert.equal(doc.getElementById('shell').inert, true);
assert.equal(doc.getElementById('disclaimerAcceptBtn').disabled, true);
receive('appInfo',{appVersion:'0.2.0',dataRoot:'test',backupRoot:'test',database:'test',disclaimerAccepted:false,disclaimerText:'TERMS'});
assert.equal(doc.getElementById('disclaimerGate').hidden,false);
doc.getElementById('disclaimerAcceptBtn').click();
assert.equal(sent.at(-1).action,'acceptDisclaimer');
assert.equal(doc.getElementById('shell').inert,true); // host acknowledgement required
receive('disclaimerAccepted',{});
assert.equal(doc.getElementById('shell').inert,false);
assert.equal(doc.getElementById('disclaimerGate').hidden,true);
receive('manifest',{version:'test',targets:[{id:'BH',label:'Body',portHint:'left',sha256:'a'.repeat(64),prepared:true}],releases:['test']});
receive('backups',[{id:1,role:'BH',fileName:'backup.bin',exists:true,createdUtc:new Date().toISOString(),sha256:'b'.repeat(64),source:'local'}]);
receive('busy',{value:true});
assert.equal(doc.querySelector('.flash-btn').disabled,true);
assert.equal(doc.querySelector('.restore').disabled,true);
receive('busy',{value:false});
assert.equal(doc.querySelector('.flash-btn').disabled,false);
assert.equal(doc.querySelector('.restore').disabled,false);
for(const nav of doc.querySelectorAll('.nav-item')){
 nav.click();
 assert.equal(doc.querySelectorAll('.page.active').length,1);
 assert.equal(doc.querySelector('.page.active').id,'page-'+nav.dataset.page);
 assert.ok(doc.querySelector('.page.active').contains(doc.getElementById('operationCard')));
}
receive('operationProgress',{message:'read',progress:41});
assert.equal(doc.getElementById('operationProgress').style.width,'41%');
receive('operationFailed',{message:'failure'});
assert.match(doc.getElementById('operationText').textContent,/failure/);
receive('log',{message:'<script>bad</script>',level:'ERROR',category:'TEST',createdUtc:new Date().toISOString()});
assert.equal(doc.getElementById('dashboardLogs').querySelector('script'),null);
receive('appInfo',{appVersion:'0.2.0',dataRoot:'test',backupRoot:'test',database:'test',disclaimerAccepted:false,disclaimerText:'NEW TERMS'});
assert.equal(doc.getElementById('shell').inert,true);
assert.equal(doc.getElementById('disclaimerGate').hidden,false);
const ids=[...doc.querySelectorAll('[id]')].map(n=>n.id);
assert.equal(ids.length,new Set(ids).size);
console.log('PASS: startup gate, host acknowledgement, version gate, navigation, operation visibility, busy reset, progress, errors, log escaping, unique IDs');
w.close();
